### ISSUE TITLE
Self-remove after everything is done

### ISSUE THREAD

**Issue by DandyDrop** [AWeirdDev/replit-ffmpeg#1]
As it is a program that, as far as I understand, usually gets used just once, it would have been convenient if it asked user if he wants it to self-remove after printing "all done"

**Comment by AWeirdDev** [comment]
Hi! If I understood correctly, self-remove is [referenced here on this line](https://github.com/AWeirdScratcher/replit-ffmpeg/blob/main/replit_ffmpeg/installer.py#L166C76-L166C76). This is a confirmation message to ask the user whether to self-remove the contents you might not need for Replit.

However, if by "self-remove" you meant to remove the package itself, it might be impossible (and not so efficient) to do it in-code. If you'd like to uninstall the package, I recommend to use `pip uninistall`.

Thanks!
